### PR TITLE
[GH-#56] code coverage tool, for ci to work

### PR DESCRIPTION
**Pull request by thepiwo**

### CODE REVIEW

**Comment by thepiwo** [comment]
@gspasov what do we need the http for at all? This is failing the test, as there is no node running

**Comment by gspasov** [comment]
@thepiwo We made the module for getting the endpoints of the core. For now we just made it for getting the info. Do you think that we rushed with implementing it?

**Comment by thepiwo** [comment]
@gspasov no it's fine, we should just make the unit tests work without a node being accessible, maybe just remove it.

**Comment by gspasov** [comment]
@thepiwo  Ok, I'll fix the test and commit on this branch
.

**Pull request merged**
